-- MySQL Script generated by MySQL Workbench
-- Fri Nov 30 16:27:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema erhuo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erhuo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `erhuo` DEFAULT CHARACTER SET utf8 ;
USE `erhuo` ;

-- -----------------------------------------------------
-- Table `erhuo`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erhuo`.`User` (
  `UserPhone` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserPhone`),
  UNIQUE INDEX `UserPhone_UNIQUE` (`UserPhone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erhuo`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erhuo`.`UserInfo` (
  `UserPhone` VARCHAR(45) NOT NULL,
  `Userphoto` VARCHAR(100) NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `UserSex` VARCHAR(45) NULL,
  `UserSignature` VARCHAR(500) NULL,
  `UserQQ` VARCHAR(500) NULL,
  `UserPlace` VARCHAR(45) NULL,
  `UserData` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`UserPhone`),
  UNIQUE INDEX `UserPhone_UNIQUE` (`UserPhone` ASC) VISIBLE,
  CONSTRAINT `UserInfo_User_FK`
    FOREIGN KEY (`UserPhone`)
    REFERENCES `erhuo`.`User` (`UserPhone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erhuo`.`Goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erhuo`.`Goods` (
  `GoodsID` INT NOT NULL AUTO_INCREMENT,
  `UserPhone` VARCHAR(45) NOT NULL,
  `GoodsTitle` VARCHAR(45) NOT NULL,
  `GoodsMoney1` VARCHAR(10) NOT NULL,
  `GoodsMoney2` VARCHAR(10) NULL,
  `GoodsDescribe` VARCHAR(500) NOT NULL,
  `GoodsType` VARCHAR(20) NULL,
  `GoodsSituation` VARCHAR(10) NULL,
  `GoodsImg1` VARCHAR(100) NULL,
  `GoodsImg2` VARCHAR(100) NULL,
  `GoodsImg3` VARCHAR(100) NULL,
  `GoodsImg4` VARCHAR(100) NULL,
  `GoodsImg5` VARCHAR(100) NULL,
  `GoodsUserName` VARCHAR(20) NOT NULL,
  `GoodsUserPhone` VARCHAR(45) NOT NULL,
  `GoodsUserQQ` VARCHAR(45) NULL,
  `GoodsUserPlace` VARCHAR(45) NOT NULL,
  `GoodsData` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`GoodsID`),
  INDEX `GoodsUser_id_idx` (`GoodsID` ASC, `UserPhone` ASC) VISIBLE,
  CONSTRAINT `Goods_User_FK`
    FOREIGN KEY (`UserPhone`)
    REFERENCES `erhuo`.`User` (`UserPhone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS `erhuo`.`Administrator` (
  `AdminID` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AdminID`),
  UNIQUE INDEX `AdminID_UNIQUE` (`AdminID` ASC) VISIBLE)
ENGINE = InnoDB;
